### ISSUE TITLE
/failtransfers crashes the node

### ISSUE THREAD

**Issue by gofman8** [RGB-Tools/rgb-lightning-node#40]
### Run nodes A,B
Run nodes A,B call `/init` & `/unlock` for each node. Send BTC to Nodes

1. Issue TUSD asset (200 tokens) (RGB on-chain API)
2. Create Asset (Node A) `/createutxos` and `/issueassetnia`
3. Open channel with Node B with 50 tokens (Node A Call `/openchannel` )
4. Node B call `/createutxos`
5. Node B call `/rgbinvoice`
```json
{
  "min_confirmations": 1,
  "asset_id": "rgb:AqUzv1MD-7RXCjG2-HxkTY6v-Ilw9syI-6HZGgtS-xgj7juE",
  "duration_seconds": 86400
}
```

Responce:
```json
{
  "recipient_id": "bcrt:utxob:GSJU!tMt-z7yQMb5-evP1Y$E-VI2hW62-xSEt3Yk-o$RcRei-$yMie",
  "invoice": "rgb:AqUzv1MD-7RXCjG2-HxkTY6v-Ilw9syI-6HZGgtS-xgj7juE/RGB20Fixed/bcrt:utxob:GSJU!tMt-z7yQMb5-evP1Y$E-VI2hW62-xSEt3Yk-o$RcRei-$yMie?expiry=1729275770&endpoints=rpc://regtest.thunderstack.org:3000/json-rpc",
  "expiration_timestamp": 1729275770
}
```
6. check `/listtransfers`

Responce:
```json
{
  "transfers": [
    {
      "idx": 1,
      "created_at": 1729189370,
      "updated_at": 1729189370,
      "status": "WaitingCounterparty",
      "amount": 0,
      "kind": "ReceiveBlind",
      "txid": null,
      "recipient_id": "bcrt:utxob:GSJU!tMt-z7yQMb5-evP1Y$E-VI2hW62-xSEt3Yk-o$RcRei-$yMie",
      "receive_utxo": "e8adce80b2b2d3c73b78efcbfb3a749d38582cf913c9b5659a73bfab93caa7d1:0",
      "change_utxo": null,
      "expiration": 1729275770,
      "transport_endpoints": [
        {
          "endpoint": "http://regtest.thunderstack.org:3000/json-rpc",
          "transport_type": "JsonRpc",
          "used": false
        }
      ]
    }
  ]
}
```

7. call `/failtransfers`

Request:
```json
{
  "batch_transfer_idx": 1,
  "no_asset_only": false,
  "skip_sync": false
}
```
after this request `/failtransfers` the node crashes and this error is in the logs

```bash
[2024-10-17T21:25:03.541+03:00] | thread 'tokio-runtime-worker' panicked at src/utils.rs:306:14:
[2024-10-17T21:25:03.541+03:00] | called `Result::unwrap()` on an `Err` value: RecvError(())
[2024-10-17T21:25:03.540+03:00] | thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.1/src/runtime/blocking/shutdown.rs:51:21:
[2024-10-17T21:25:03.540+03:00] | Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
[2024-10-17T21:25:03.540+03:00] | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by zoedberg** [comment]
Thanks for reporting this! The error was due to a blocking call made by rgb-lib. Fixed in cc99963
